#!/bin/bash
set -e

build_daemon_controller=true
build_crash_watch=true

source lib/bashlib
load_general_config
use_dummy_gpg
require_running_as_psg_apt_automation_user

header "Obtaining lock file"
export build_daemon_controller
export build_crash_watch
exec chpst -l /var/cache/passenger_apt_automation/lock bash internal/import_misc_packages.sh
