#!/bin/bash
set -e

BASE_DIR=`dirname "$0"`
BASE_DIR=`cd "$BASE_DIR"; pwd`

GIT_URL="$1"
REPO_DIR="$2"
APT_DIR="$3"
REF=${4:-origin/master}
DEFAULT_NAMESPACE=`basename "$REPO_DIR" | sed -E 's/\..*?$//'`
NAMESPACE=${DEFAULT_NAMESPACE:-default}
source configuration
export PKG_DIR=/tmp/passenger_apt_build.$NAMESPACE

set -x

if [[ -e "$REPO_DIR" ]]; then
	echo "Updating repository..."
	cd "$REPO_DIR"
	if [[ "`git config remote.origin.url`" != "$GIT_URL" ]]; then
		echo "Git repository URL does not match!"
		exit 1
	fi
	git fetch
	rm -rf *
else
	echo "Cloning repository..."
	git clone "$GIT_URL" "$REPO_DIR"
	cd "$REPO_DIR"
fi
git reset --hard "$REF"

echo "Building Phusion Passenger packages..."
rm -rf "$PKG_DIR"
mkdir -p "$PKG_DIR"
rm -rf ~/pbuilder/*_result/*
unset USE_CCACHE
drake debian:source_packages
drake debian:binary_packages -j$CONCURRENCY_LEVEL

echo "Building Nginx packages..."
cd "$BASE_DIR"
export PASSENGER_DIR=$REPO_DIR
./create_nginx_package source_packages
./create_nginx_package binary_packages -j$CONCURRENCY_LEVEL

echo "Signing packages..."
cd "$BASE_DIR"
export PATH="$BASE_DIR/dummygpg:$PATH"
debsign -k$SIGNING_KEY $PKG_DIR/nginx*.changes
debsign -k$SIGNING_KEY $PKG_DIR/official/*.changes
debsign -k$SIGNING_KEY ~/pbuilder/*_result/*.changes

echo "Importing packages into APT repository..."
rm -rf "$APT_DIR.tmp" "$APT_DIR.old"
cp -dpR "$APT_DIR" "$APT_DIR.tmp"
cd "$APT_DIR.tmp"
for DIST in $DEBIAN_DISTROS; do
	for ARCH in $DEBIAN_ARCHS; do
		if [[ $ARCH == amd64 ]]; then
			pbase_name="$DIST"
		else
			pbase_name="$DIST-$ARCH"
		fi
		result_dir="$HOME/pbuilder/${pbase_name}_result"
		reprepro --keepunusednewfiles -Vb . includedeb $DIST $result_dir/*_$ARCH.deb
	done
	reprepro --keepunusednewfiles -Vb . includedeb $DIST $HOME/pbuilder/${DIST}_result/*_all.deb
	for F in $HOME/pbuilder/${DIST}_result/*.dsc; do
		reprepro --keepunusednewfiles -Vb . includedsc $DIST $F
	done
done
find . -name Release.gpg -print0 | xargs -0 rm -f
find . -name Release -exec gpg --batch --sign --detach-sign --armor --local-user $SIGNING_KEY --output \{\}.gpg \{\} \;
cd ..
mv "$APT_DIR" "$APT_DIR.old"
mv "$APT_DIR.tmp" "$APT_DIR"
rm -rf "$APT_DIR.old"
