#!/bin/bash
# Builds packages for Phusion Passenger and Nginx.

set -e


##### Parse parameters #####

export GIT_URL="$1"
export PROJECT_NAME="$2"
export REF=${3:-origin/master}

if [[ "$GIT_URL" = "" || "$PROJECT_NAME" = "" ]]; then
	echo "Usage: ./new_release GIT_URL PROJECT_NAME [REF]"
	exit 1
fi


##### Initialization #####

export BASE_DIR=`dirname "$0"`
export BASE_DIR=`cd "$BASE_DIR"; pwd`
source "$BASE_DIR/lib/bashlib"

load_general_config
use_dummy_gpg
require_running_as_psg_apt_automation_user
validate_project_name "$PROJECT_NAME"

export WORK_DIR="/var/cache/passenger_apt_automation/$PROJECT_NAME.workdir"
export PKG_DIR="$WORK_DIR/pkg"
export PBUILDFOLDER="$WORK_DIR/pbuilder"

export PROJECT_GIT_REPO_DIR="/var/cache/passenger_apt_automation/$PROJECT_NAME.git"
export PROJECT_APT_REPO_DIR="$APT_REPO_DIR/$PROJECT_NAME.apt"

unset CCACHE

shopt -s dotglob

echo "# Initializing..."
mkdir -p "$WORK_DIR"
echo -n > "$WORK_DIR/stage"
echo $$ > "$WORK_DIR/pid"


##### Run main program #####

set -o pipefail

trap "stage Error error; exit 1" ERR
stage "Obtaining lock..." obtaining_lock

chpst -l /var/cache/passenger_apt_automation/lock \
	bash internal/new_release.sh 2>&1 | \
	gawk '{ print strftime("%Y-%m-%d %H:%M:%S  "), $0; fflush(); }' | \
	tee "$WORK_DIR/full.log"

stage "Done" done
