#!/bin/bash
# Used by Jenkins

set -e

NAME="$1"

if [[ "$NAME" = "" ]]; then
	echo "Usage: ./reset_test_repo <NAME>"
	exit 1
fi

set -x

release_name=`date +%Y%m%d-%H%M%S`
rm -rf "$NAME.apt"/releases/*
cp -dpR "$NAME.apt/first_release" "$NAME.apt/releases/$release_name"
rm "$NAME.apt/current"
cd "$NAME.apt"
ln -s "releases/$release_name" current
