#!/bin/bash
set -e

SELFDIR=$(dirname "$0")
SELFDIR=$(cd "$SELFDIR" && pwd)
# shellcheck source=internal/lib/library.sh
source "$SELFDIR/internal/lib/library.sh"
# shellcheck source=internal/lib/distro_info.sh
source "$SELFDIR/internal/lib/distro_info.sh"

PASSENGER_DIR=
WORK_DIR=
CACHE_DIR=
OUTPUT_DIR=
CONCURRENCY=1
DISTRIBUTIONS="$DEFAULT_DISTROS"
ARCH=$(uname -m)
FETCH_PASSENGER_TARBALL_FROM_CACHE=true
CLEAR_WORK_DIR=true
SHOW_OVERVIEW_PERIODICALLY=false
SHOW_BACKTRACES=false

function usage()
{
    echo "Usage: ./shell [OPTIONS]"
    echo "Open a shell in a build box container."
    echo
    echo "Required options:"
    echo "  -p DIR     Path to Passenger source directory"
    echo "  -w DIR     Path to work directory (for temporary files)"
    echo "  -c DIR     Path to cache directory"
    echo "  -o DIR     Path in which to store build products"
    echo
    echo "Optional options:"
    echo "  -j NUM     Set build concurrency. Default: 1"
    echo "  -d NAMES   Shell for building only given distributions. This is a space-separated list"
    echo "             of distribution names."
    echo "             Default: $DEFAULT_DISTROS"
    echo "  -a NAME    Shell for building given architecture. This must be a single architecture"
    echo "             name, not a list."
    echo "             Default: $ARCH, allowed values: arm64, amd64"
    echo "  -R         Do not fetch Passenger tarball from cache"
    echo "  -N         Do not clear work directory on startup"
    echo "  -O         Periodically show progress overview"
    echo "  -t         Show backtraces on error"
    echo
    echo "  -h         Show usage"
}

function parse_options()
{
    local OPTIND=1
    local opt
    while getopts "p:w:c:o:j:d:a:RNOth" opt; do
        case "$opt" in
            p)
                PASSENGER_DIR="$OPTARG"
                ;;
            w)
                WORK_DIR="$OPTARG"
                ;;
            c)
                CACHE_DIR="$OPTARG"
                ;;
            o)
                OUTPUT_DIR="$OPTARG"
                ;;
            j)
                CONCURRENCY=$OPTARG
                ;;
            d)
                DISTRIBUTIONS="$OPTARG"
                ;;
            a)
                ARCH=($OPTARG)
                ;;
            t)
                SHOW_BACKTRACES=true
                ;;
            R)
                FETCH_PASSENGER_TARBALL_FROM_CACHE=false
                ;;
            N)
                CLEAR_WORK_DIR=false
                ;;
            O)
                SHOW_OVERVIEW_PERIODICALLY=true
                ;;
            h)
                usage
                exit
                ;;
            *)
                return 1
                ;;
        esac
    done

    (( OPTIND -= 1 )) || true
    shift $OPTIND || true

    BUILDBOX_IMAGE=$(get_buildbox_image)

    if [[ "$PASSENGER_DIR" = "" ]]; then
        echo "ERROR: please specify a Passenger source directory with -p."
        exit 1
    fi
    if [[ ! -e "$PASSENGER_DIR" ]]; then
        echo "ERROR: $PASSENGER_DIR does not exist."
        exit 1
    fi
    if [[ 1 != "${#ARCH[@]}" ]]; then
        echo "ERROR: $ARCH must be a single arch name."
        exit 1
    fi
    if [[ "$WORK_DIR" = "" ]]; then
        echo "ERROR: please specify a work directory with -w."
        exit 1
    fi
    if [[ "$CACHE_DIR" = "" ]]; then
        echo "ERROR: please specify a cache directory with -c."
        exit 1
    fi
    if [[ "$OUTPUT_DIR" = "" ]]; then
        echo "ERROR: please specify an output directory with -o."
        exit 1
    fi
}

parse_options "$@"

DISTRO_NGINXS=()
for distro in $DISTRIBUTIONS; do
    export DOCKER_CLI_EXPERIMENTAL=enabled
    if docker manifest inspect "debian:$distro" >/dev/null 2>&1; then
        kind="debian"
    else
        kind="ubuntu"
    fi
    version=$(docker run "$kind:$distro" bash -c 'apt-get update >/dev/null && apt-cache policy nginx-core' | awk '/Candidate:/{print $NF}')
    DISTRO_NGINXS+=("$distro:$version")
done
PASSENGER_DIR=$(absolute_path "$PASSENGER_DIR")
WORK_DIR=$(absolute_path "$WORK_DIR")
CACHE_DIR=$(absolute_path "$CACHE_DIR")
OUTPUT_DIR=$(absolute_path "$OUTPUT_DIR")

run mkdir -p "$WORK_DIR"
run mkdir -p "$CACHE_DIR"
run mkdir -p "$CACHE_DIR/pbuilder/ccache"
run mkdir -p "$OUTPUT_DIR"

echo "+ Initializing ccache directory"
verbose_run docker run \
            --rm \
            -v "$SELFDIR:/system:ro" \
            -v "$CACHE_DIR:/cache" \
            -e "DISTRIBUTIONS=$DISTRIBUTIONS" \
            -e "ARCHITECTURES=$ARCH" \
            -e "APP_UID=$(/usr/bin/id -u)" \
            -e "APP_GID=$(/usr/bin/id -g)" \
            --platform "linux/$ARCH" \
            "$BUILDBOX_IMAGE" \
            /system/internal/scripts/inituidgid.sh \
            /system/internal/scripts/initccache.sh

echo "-------- Entering Docker container --------"
exec docker run \
     --rm -t -i \
     --privileged \
     -v "$SELFDIR:/system:ro" \
     -v "$PASSENGER_DIR:/passenger:ro" \
     -v "$WORK_DIR:/work" \
     -v "$CACHE_DIR:/cache" \
     -v "$OUTPUT_DIR:/output" \
     -v "$CACHE_DIR/pbuilder:/var/cache/pbuilder" \
     -e "DISTRIBUTIONS=$DISTRIBUTIONS" \
     -e "DISTRO_NGINXS=${DISTRO_NGINXS[*]}" \
     -e "ARCHITECTURES=$ARCH" \
     -e "SHOW_OVERVIEW_PERIODICALLY=$SHOW_OVERVIEW_PERIODICALLY" \
     -e "FETCH_PASSENGER_TARBALL_FROM_CACHE=$FETCH_PASSENGER_TARBALL_FROM_CACHE" \
     -e "APP_UID=$(/usr/bin/id -u)" \
     -e "APP_GID=$(/usr/bin/id -g)" \
     -e "LC_CTYPE=C.UTF-8" \
     -e "CONCURRENCY=$CONCURRENCY" \
     -e "CLEAR_WORK_DIR=$CLEAR_WORK_DIR" \
     --platform "linux/$ARCH" \
     "$BUILDBOX_IMAGE" \
     /sbin/my_init --quiet --skip-runit --skip-startup-files -- \
     /system/internal/scripts/inituidgid.sh \
     /system/internal/shell/preinit.sh \
     /sbin/setuser app \
     /bin/bash -l
