#!/bin/bash
set -e
BASE_DIR=`dirname "$0"`
BASE_DIR=`cd "$BASE_DIR"; pwd`
export PATH="$BASE_DIR/lib/dummygpg:$PATH"
source "$BASE_DIR/config/general"

DIR="$1"
if [[ "$DIR" = "" ]]; then
	echo "Usage: ./sign_repo DIR"
	echo "(Re)sign an APT repostory"
	exit 1
fi

set -x
cd "$DIR"
find . -name Release.gpg -print0 | xargs -0 rm -f
find . -name Release -exec gpg --batch --sign --detach-sign --armor --local-user $SIGNING_KEY --output \{\}.gpg \{\} \;
