#!/bin/bash
set -e

if [[ "$1" == "--version" ]]; then
	exec gpg --version
fi

source configuration
output_file=
file=

for arg in "$@"; do
	if [[ "$arg" =~ ^/.*\.asc$ ]]; then
		output_file="$arg"
	elif [[ "$arg" =~ ^/ ]]; then
		file="$arg"
	fi
done

exec gpg --armor --local-user $SIGNING_KEY --clearsign --no-show-policy-url --output "$output_file" "$file"
