#!/bin/bash
set -e
if [[ "$1" == "--version" ]]; then
	exec /usr/bin/gpg --version
else
	BASE_DIR=`dirname "$0"`
	BASE_DIR=`cd "$BASE_DIR/.."; pwd`
	exec /usr/bin/gpg --batch --passphrase-fd 3 "$@" 3<"$BASE_DIR/passphrase"
fi
