#!/bin/bash
# DO NOT EDIT!!
# 
# This file is automatically generated from internal/lib/distro_info.sh.erb,
# using definitions from internal/lib/distro_info.rb and docker_image_info.sh.
# 
# Edit those and regenerate distro_info.sh by running:
# internal/scripts/regen_distro_info_script.sh

# shellcheck disable=SC2034
DEFAULT_DISTROS="focal jammy mantic buster bullseye bookworm"


function to_distro_codename()
{
	local INPUT="$1"
	INPUT=${INPUT#ubuntu-}
	INPUT=${INPUT#ubuntu}
	INPUT=${INPUT#debian-}
	INPUT=${INPUT#debian}

	local AWK_SCRIPT='$1 ~ PATTERN || $2 ~ PATTERN {print $2}'

	local VERSION=$(cut -d, -f 1,3 /usr/share/distro-info/*.csv | awk -F, -vPATTERN="^$INPUT( LTS|\\\\.0)?\$" "$AWK_SCRIPT")
	if [ -n "$VERSION" ]; then
		echo $VERSION
		return 0
	fi

	return 1
}

function get_buildbox_image()
{
	echo "phusion/passenger_apt_automation_buildbox:2.1.0"
}

function to_testbox_image()
{
	local INPUT="$1"
	INPUT=${INPUT#ubuntu-}
	INPUT=${INPUT#ubuntu}
	INPUT=${INPUT#debian-}
	INPUT=${INPUT#debian}
	INPUT=$(to_distro_codename $INPUT)
	local AWK_SCRIPT='$1 ~ PATTERN || $2 ~ PATTERN {print $1}'

	local VERSION=$(cut -d, -f 1,3 /usr/share/distro-info/ubuntu.csv | awk -F, -vPATTERN="^$INPUT( LTS)?\$" "$AWK_SCRIPT")
	if [ -n "$VERSION" ]; then
		  VERSION=${VERSION% LTS}
		  echo phusion/passenger_apt_automation_testbox_ubuntu_${VERSION/./_}:2.1.2
		  return
	fi

	VERSION=$(cut -d, -f 1,3 /usr/share/distro-info/debian.csv | awk -F, -vPATTERN="^$INPUT(\\\\.0)?\$" "$AWK_SCRIPT")
	if [ -n "$VERSION" ]; then
		  VERSION=${VERSION%.0}
		  echo phusion/passenger_apt_automation_testbox_debian_${VERSION/./_}:2.1.2
		  return
	fi

	return 1
}

function ubuntu_gte()
{
	local AWK_SCRIPT='$2 ~ PATTERN || $1 ~ PATTERN {print $3}'
	local REL_1=$(cut -d, -f 1,3,5 /usr/share/distro-info/ubuntu.csv | awk -F, -vPATTERN="^$1( LTS)?\$" "$AWK_SCRIPT")
	local REL_2=$(cut -d, -f 1,3,5 /usr/share/distro-info/ubuntu.csv | awk -F, -vPATTERN="^$2( LTS)?\$" "$AWK_SCRIPT")
	echo -e "$REL_1\n$REL_2" | sort -rC
}

function debian_gte()
{
	local AWK_SCRIPT='$2 ~ PATTERN || $1 ~ PATTERN {print $3}'
	local REL_1=$(cut -d, -f 1,3,5 /usr/share/distro-info/debian.csv | awk -F, -vPATTERN="^$1(\\\\.0)?\$" "$AWK_SCRIPT")
	local REL_2=$(cut -d, -f 1,3,5 /usr/share/distro-info/debian.csv | awk -F, -vPATTERN="^$2(\\\\.0)?\$" "$AWK_SCRIPT")
	echo -e "$REL_1\n$REL_2" | sort -rC
}

function dynamic_module_supported()
{
	local CODENAME="$(to_distro_codename "$1")"

	if ubuntu_gte "$CODENAME" artful; then
		  echo true
		  return
	fi

	if debian_gte "$CODENAME" stretch; then
		  echo true
		  return
	fi

	echo false
}

function known_distro ()
{
	local AWK_SCRIPT='BEGIN {err = 1} $2 ~ PATTERN || $1 ~ PATTERN {err = 0} END {exit err}'
	cut -d, -f 1,3 /usr/share/distro-info/*.csv | awk -F, -vPATTERN="^$1( LTS|\\\\.0)?\$" "$AWK_SCRIPT"
}
