
# DO NOT EDIT!!
# 
# This file is automatically generated from internal/lib/distro_info.sh.erb,
# using definitions in internal/lib/distro_info.rb.
# 
# If you want to change this file, please edit one of those other two files,
# then regenerate distro_info.sh by running
# internal/scripts/regen_distro_info_script.sh.

DEFAULT_DISTROS="precise trusty vivid wily squeeze wheezy jessie"

function to_distro_codename()
{
	local INPUT="$1"

	
		if [[ "$INPUT" = "lucid"
			|| "$INPUT" = "ubuntu10.04"
			|| "$INPUT" = "ubuntu-10.04" ]]
		then
			echo "lucid"
			return
		fi
	
		if [[ "$INPUT" = "maverick"
			|| "$INPUT" = "ubuntu10.10"
			|| "$INPUT" = "ubuntu-10.10" ]]
		then
			echo "maverick"
			return
		fi
	
		if [[ "$INPUT" = "natty"
			|| "$INPUT" = "ubuntu11.04"
			|| "$INPUT" = "ubuntu-11.04" ]]
		then
			echo "natty"
			return
		fi
	
		if [[ "$INPUT" = "oneiric"
			|| "$INPUT" = "ubuntu11.10"
			|| "$INPUT" = "ubuntu-11.10" ]]
		then
			echo "oneiric"
			return
		fi
	
		if [[ "$INPUT" = "precise"
			|| "$INPUT" = "ubuntu12.04"
			|| "$INPUT" = "ubuntu-12.04" ]]
		then
			echo "precise"
			return
		fi
	
		if [[ "$INPUT" = "quantal"
			|| "$INPUT" = "ubuntu12.10"
			|| "$INPUT" = "ubuntu-12.10" ]]
		then
			echo "quantal"
			return
		fi
	
		if [[ "$INPUT" = "raring"
			|| "$INPUT" = "ubuntu13.04"
			|| "$INPUT" = "ubuntu-13.04" ]]
		then
			echo "raring"
			return
		fi
	
		if [[ "$INPUT" = "saucy"
			|| "$INPUT" = "ubuntu13.10"
			|| "$INPUT" = "ubuntu-13.10" ]]
		then
			echo "saucy"
			return
		fi
	
		if [[ "$INPUT" = "trusty"
			|| "$INPUT" = "ubuntu14.04"
			|| "$INPUT" = "ubuntu-14.04" ]]
		then
			echo "trusty"
			return
		fi
	
		if [[ "$INPUT" = "utopic"
			|| "$INPUT" = "ubuntu14.10"
			|| "$INPUT" = "ubuntu-14.10" ]]
		then
			echo "utopic"
			return
		fi
	
		if [[ "$INPUT" = "vivid"
			|| "$INPUT" = "ubuntu15.04"
			|| "$INPUT" = "ubuntu-15.04" ]]
		then
			echo "vivid"
			return
		fi
	
		if [[ "$INPUT" = "wily"
			|| "$INPUT" = "ubuntu15.10"
			|| "$INPUT" = "ubuntu-15.10" ]]
		then
			echo "wily"
			return
		fi
	
	
		if [[ "$INPUT" = "squeeze"
			|| "$INPUT" = "debian6"
			|| "$INPUT" = "debian-6" ]]
		then
			echo "squeeze"
			return
		fi
	
		if [[ "$INPUT" = "wheezy"
			|| "$INPUT" = "debian7"
			|| "$INPUT" = "debian-7" ]]
		then
			echo "wheezy"
			return
		fi
	
		if [[ "$INPUT" = "jessie"
			|| "$INPUT" = "debian8"
			|| "$INPUT" = "debian-8" ]]
		then
			echo "jessie"
			return
		fi
	
		if [[ "$INPUT" = "stretch"
			|| "$INPUT" = "debian9"
			|| "$INPUT" = "debian-9" ]]
		then
			echo "stretch"
			return
		fi
	
		if [[ "$INPUT" = "buster"
			|| "$INPUT" = "debian10"
			|| "$INPUT" = "debian-10" ]]
		then
			echo "buster"
			return
		fi
	

	return 1
}

function to_testbox_image()
{
	local INPUT="$1"

	
		if [[ "$INPUT" = "lucid"
			|| "$INPUT" = "ubuntu10.04"
			|| "$INPUT" = "ubuntu-10.04" ]]
		then
			echo phusion/passenger_apt_automation_testbox_ubuntu_10_04
			return
		fi
	
		if [[ "$INPUT" = "maverick"
			|| "$INPUT" = "ubuntu10.10"
			|| "$INPUT" = "ubuntu-10.10" ]]
		then
			echo phusion/passenger_apt_automation_testbox_ubuntu_10_10
			return
		fi
	
		if [[ "$INPUT" = "natty"
			|| "$INPUT" = "ubuntu11.04"
			|| "$INPUT" = "ubuntu-11.04" ]]
		then
			echo phusion/passenger_apt_automation_testbox_ubuntu_11_04
			return
		fi
	
		if [[ "$INPUT" = "oneiric"
			|| "$INPUT" = "ubuntu11.10"
			|| "$INPUT" = "ubuntu-11.10" ]]
		then
			echo phusion/passenger_apt_automation_testbox_ubuntu_11_10
			return
		fi
	
		if [[ "$INPUT" = "precise"
			|| "$INPUT" = "ubuntu12.04"
			|| "$INPUT" = "ubuntu-12.04" ]]
		then
			echo phusion/passenger_apt_automation_testbox_ubuntu_12_04
			return
		fi
	
		if [[ "$INPUT" = "quantal"
			|| "$INPUT" = "ubuntu12.10"
			|| "$INPUT" = "ubuntu-12.10" ]]
		then
			echo phusion/passenger_apt_automation_testbox_ubuntu_12_10
			return
		fi
	
		if [[ "$INPUT" = "raring"
			|| "$INPUT" = "ubuntu13.04"
			|| "$INPUT" = "ubuntu-13.04" ]]
		then
			echo phusion/passenger_apt_automation_testbox_ubuntu_13_04
			return
		fi
	
		if [[ "$INPUT" = "saucy"
			|| "$INPUT" = "ubuntu13.10"
			|| "$INPUT" = "ubuntu-13.10" ]]
		then
			echo phusion/passenger_apt_automation_testbox_ubuntu_13_10
			return
		fi
	
		if [[ "$INPUT" = "trusty"
			|| "$INPUT" = "ubuntu14.04"
			|| "$INPUT" = "ubuntu-14.04" ]]
		then
			echo phusion/passenger_apt_automation_testbox_ubuntu_14_04
			return
		fi
	
		if [[ "$INPUT" = "utopic"
			|| "$INPUT" = "ubuntu14.10"
			|| "$INPUT" = "ubuntu-14.10" ]]
		then
			echo phusion/passenger_apt_automation_testbox_ubuntu_14_10
			return
		fi
	
		if [[ "$INPUT" = "vivid"
			|| "$INPUT" = "ubuntu15.04"
			|| "$INPUT" = "ubuntu-15.04" ]]
		then
			echo phusion/passenger_apt_automation_testbox_ubuntu_15_04
			return
		fi
	
		if [[ "$INPUT" = "wily"
			|| "$INPUT" = "ubuntu15.10"
			|| "$INPUT" = "ubuntu-15.10" ]]
		then
			echo phusion/passenger_apt_automation_testbox_ubuntu_15_10
			return
		fi
	
	
		if [[ "$INPUT" = "squeeze"
			|| "$INPUT" = "debian6"
			|| "$INPUT" = "debian-6" ]]
		then
			echo phusion/passenger_apt_automation_testbox_debian_6
			return
		fi
	
		if [[ "$INPUT" = "wheezy"
			|| "$INPUT" = "debian7"
			|| "$INPUT" = "debian-7" ]]
		then
			echo phusion/passenger_apt_automation_testbox_debian_7
			return
		fi
	
		if [[ "$INPUT" = "jessie"
			|| "$INPUT" = "debian8"
			|| "$INPUT" = "debian-8" ]]
		then
			echo phusion/passenger_apt_automation_testbox_debian_8
			return
		fi
	
		if [[ "$INPUT" = "stretch"
			|| "$INPUT" = "debian9"
			|| "$INPUT" = "debian-9" ]]
		then
			echo phusion/passenger_apt_automation_testbox_debian_9
			return
		fi
	
		if [[ "$INPUT" = "buster"
			|| "$INPUT" = "debian10"
			|| "$INPUT" = "debian-10" ]]
		then
			echo phusion/passenger_apt_automation_testbox_debian_10
			return
		fi
	

	return 1
}
