#!/usr/bin/env ruby
def quiet_sh(*command)
	if !system(*command)
		abort "*** Command failed: #{command.join(' ')}"
	end
end

if !ARGV[0]
	abort "Usage: ./diff_nginx_debian <PATH TO DEBIAN DIR>\n" +
		"View differences between our Debian packaging directory and one provided by Debian."
end

begin
	quiet_sh "cp -pR nginx-debian nginx-debian.tmp"
	Dir["nginx-debian.tmp/**/*.template"].each do |filename|
		File.rename(filename, filename.sub(/.template$/, ''))
	end
	system("git", "diff", "nginx-debian.tmp", ARGV[0])
ensure
	quiet_sh "rm -rf nginx-debian.tmp"
end