require_relative 'rakefile_support'
require_relative '../lib/tracking'

initialize_rakefile!
initialize_tracking_database!(SHOW_OVERVIEW_PERIODICALLY)


##### Source tarballs and build environment initialization #####

SOURCE_TASKS = [ 'source:passenger', 'source:nginx_dev' ]

register_tracking_category(:preparation, 'Preparation')

namespace :source do
  DISTROS.each do |distro|
    register_tracking_task(:preparation, "passenger:#{distro}")
    desc "Get Passenger orig tarball"
    task("passenger:#{distro}") do
      track_task(:preparation, "passenger:#{distro}") do |task|
        tar_xz = "#{PASSENGER_DEBIAN_NAME}_#{PASSENGER_VERSION}-*#{distro}*.debian.tar.xz"
        if FETCH_PASSENGER_TARBALL_FROM_CACHE && File.exist?("/cache/#{PASSENGER_TARBALL}") && !Dir["/cache/#{tar_xz}"].empty?
          task.sh "cp /cache/#{PASSENGER_TARBALL} /work/#{PASSENGER_TARBALL}"
          task.sh "cp /cache/#{tar_xz} /work/"
        else
          task.sh "./fetch-passenger-orig-tarball.sh /work/ #{distro}",
                  PASSENGER_ENTERPRISE_DOWNLOAD_TOKEN: ENV["PASSENGER_ENTERPRISE_DOWNLOAD_TOKEN"]
          task.sh "cp /work/#{PASSENGER_TARBALL} /cache/#{PASSENGER_TARBALL}"
          task.sh "cp /work/#{tar_xz} /cache/"
        end
      end
    end
  end

  PROBLEM_DISTROS.each do |distro|
    register_tracking_task(:preparation, 'nginx_dev')
    desc "Create Nginx dev orig tarball"
    task "nginx_dev:#{distro}" do
      track_task(:preparation, 'nginx_dev') do |task|
        cache_tarball="#{NGINX_SOURCE_PACKAGE_NAME}_#{distro}_#{latest_nginx_version_upstream(distro)}.orig.tar.gz"
        work_tarball="#{NGINX_SOURCE_PACKAGE_NAME}_#{latest_nginx_version_upstream(distro)}.orig.tar.gz"
        if File.exist?("/cache/#{cache_tarball}")
          task.sh "cp /cache/#{cache_tarball} /work/#{work_tarball}"
        else
          task.sh "./download-nginx-distro-tarball.sh #{distro} /work/#{work_tarball}"
          task.sh "cp /work/#{work_tarball} /cache/#{cache_tarball}"
        end
      end
    end
  end
end

##### Source packages #####

register_tracking_category(:spkg, 'Updating source packages')

namespace :spkg do
  desc "Update all source packages for all distributions"


  ### Passenger ###

  desc "Update Passenger source packages for all distributions"
  task "passenger:all"

  DISTROS.each do |distro|
    task "passenger:all" => "passenger:#{distro}"
    task "all" => "passenger:#{distro}"

    register_tracking_task(:spkg, "passenger:#{distro}")
    desc "Update Passenger source package for #{distro}"
    task("passenger:#{distro}" => [ "source:passenger:#{distro}" ]) do
      track_task(:spkg, "passenger:#{distro}") do |task|
        task.sh "mkdir -p /work/spkg/passenger/#{distro}"
        task.sh "./update-source-package.rb",
                DISTRIBUTION: distro,
                TARBALL: PASSENGER_TARBALL,
                SOURCENAME: "#{PASSENGER_PACKAGE_NAME}-#{PASSENGER_VERSION}",
                SPKG_DIR: "/work/spkg/passenger/#{distro}",
                MAINTAINER_EMAIL: MAINTAINER_EMAIL,
                DEBIAN_EPOCH: PASSENGER_DEBIAN_EPOCH,
                DEBIAN_VENDOR_VERSION: PASSENGER_DEBIAN_VENDOR_VERSION,
                DEBIAN_HOTFIX_VERSION: PASSENGER_DEBIAN_HOTFIX_VERSION,
                PASSENGER_DEBIAN_NAME: PASSENGER_DEBIAN_NAME,
                PASSENGER_VERSION: PASSENGER_VERSION,
                NGINX_VERSION: latest_nginx_unsanitized(distro)
      end
    end
  end

  PROBLEM_DISTROS.each do |distro|
    task "passenger:#{distro}" => "passenger:#{distro}:nginx_dev"
    task "all" => "passenger:#{distro}:nginx_dev"

    register_tracking_task(:spkg, "passenger:#{distro}:nginx_dev")
    desc "Build Nginx source package for #{distro}"
    task("passenger:#{distro}:nginx_dev" => [ "source:nginx_dev:#{distro}" ]) do
      track_task(:spkg, "passenger:#{distro}:nginx_dev") do |task|
        task.sh "mkdir -p /work/spkg/nginx/#{distro}"
        nginx_dev_version = latest_nginx_version_upstream(distro)
        task.sh "./build-source-package.rb",
                SPECDIR: "/system/debian_specs/#{NGINX_SPECDIR}",
                DISTRIBUTION: distro,
                TARBALL: "#{NGINX_SOURCE_PACKAGE_NAME}_#{nginx_dev_version}.orig.tar.gz",
                SOURCENAME: "#{NGINX_SOURCE_PACKAGE_NAME}-#{nginx_dev_version}",
                SPKG_DIR: "/work/spkg/nginx/#{distro}",
                PACKAGE_VERSION: nginx_dev_version,
                DEBIAN_NAME: NGINX_DEV_DEBIAN_NAME,
                DEBIAN_EPOCH: NGINX_DEV_DEBIAN_EPOCH,
                DEBIAN_VENDOR_VERSION: latest_nginx_version_debian_revision(distro),
                DEBIAN_HOTFIX_VERSION: NGINX_DEV_DEBIAN_HOTFIX_VERSION
      end
    end
  end
end


##### Binary packages #####

register_tracking_category(:pkg, 'Building binary packages')

namespace :env do
  desc "Initialize environments for all distributions and architectures"
  task :all

  register_tracking_task(:pkg, "env:essentials")
  task :essentials do
    track_task(:pkg, "env:essentials") do |task|
      task.sh "./setup-environment-essentials.sh"
    end
  end

  DISTROS.each do |distro|
    ARCHITECTURES.each do |arch|
      task all: "#{distro}:#{arch}"

      register_tracking_task(:pkg, "env:#{distro}:#{arch}")
      desc "Initialize environment for #{distro} #{arch}"
      task "#{distro}:#{arch}" => :essentials do
        track_task(:pkg, "env:#{distro}:#{arch}") do |task|
          task.sh "./setup-environment.sh #{distro} #{arch}"
        end
      end
    end
  end
end

namespace :pkg do
  desc "Build all binary packages for all distributions and architectures"
  task :all

  directory LOCAL_POOL

  PROBLEM_DISTROS.each do |distro|
    ARCHITECTURES.each do |arch|
      directory local_repo_packages(distro, arch)

      register_tracking_task(:pkg, "prepare_local_repo:#{distro}:#{arch}")
      desc "Setup the local repo used to provide nginx-dev to build environment"
      task "prepare_local_repo:#{distro}:#{arch}" => [ LOCAL_POOL, local_repo_packages(distro, arch) ] do
        track_task(:pkg, "prepare_local_repo:#{distro}:#{arch}") do |task|
          update_staging_repo(task, distro, arch)
        end
      end
    end
  end

  ### Passenger ###

  desc "Build Passenger binary packages for all distributions and architectures"
  task "passenger:all"

  DISTROS.each do |distro|
    ARCHITECTURES.each do |arch|
      task "passenger:all" => "passenger:#{distro}:#{arch}"
      task "all" => "passenger:#{distro}:#{arch}"

      register_tracking_task(:pkg, "passenger:#{distro}:#{arch}")
      desc "Build Passenger binary package for #{distro} #{arch}"
      task("passenger:#{distro}:#{arch}" => [ "spkg:passenger:#{distro}", "env:#{distro}:#{arch}" ]) do
        track_task(:pkg, "passenger:#{distro}:#{arch}") do |task|
          extra_flags = ""
          if PROBLEM_DISTROS.include? distro
            extra_flags = "--bindmounts #{LOCAL_REPO} --othermirror 'deb [trusted=yes] file://#{LOCAL_REPO}/ #{distro} main'"
            task.sh "cd /work/spkg/passenger/#{distro} && yes | pbuilder-dist #{distro} #{arch} update --override-config #{extra_flags}"
          end
          Dir.chdir("/work/spkg/passenger/#{distro}") do
            task.sh "yes | pbuilder-dist #{distro} #{arch} build #{extra_flags} *.dsc"
            FileUtils.rm Dir["/work/pkg/#{distro}_result/*.deb"].reject { |deb| deb.include? "libnginx-mod-http" }
          end
        end
      end
    end
  end


  ### Nginx ###

  desc "Build Nginx-dev binary packages for select distributions"
  task "nginx:all"

  PROBLEM_DISTROS.each do |distro|
    ARCHITECTURES.each do |arch|
      task "nginx:all" => "nginx:#{distro}:#{arch}"
      task "all" => "nginx:#{distro}:#{arch}"
      task "passenger:#{distro}:#{arch}" => "nginx:#{distro}:#{arch}"

      register_tracking_task(:pkg, "nginx:#{distro}:#{arch}")
      desc "Build Nginx-dev binary package for #{distro} #{arch}"
      task("nginx:#{distro}:#{arch}" => [ "pkg:prepare_local_repo:#{distro}:#{arch}", "spkg:passenger:#{distro}:nginx_dev", "env:#{distro}:#{arch}" ]) do
        track_task(:pkg, "nginx:#{distro}:#{arch}") do |task|
          task.sh "cd /work/spkg/nginx/#{distro} && yes | pbuilder-dist #{distro} #{arch} build *.dsc"
          deb = Dir["/work/pkg/#{distro}_result/nginx-dev*.deb"].first
          raise "nginx-dev .deb not found" unless deb

          add_deb_to_staging_repo(deb, task, distro, arch)
        end
      end
    end
  end
end


##### Misc #####

task :clear_work_dir do
  sh "rm -rf /work/*"
end

task :start do
  initialize_tracking_database_logs!
end

task :finish do
  puts
  puts "Finished"
  TRACKING_DB.monitor.synchronize do
    TRACKING_DB.set_finished!
    dump_tracking_database
  end

  puts
  puts "Committing build products to output directory..."
  sh "rm -rf /output/*"

  files = Dir["/work/spkg/*passenger*/*/*.{gz,xz,dsc}"]
  if files.any?
    puts "Placing #{files.size} files from /work/spkg into output directory"
    files.each do |path|
      unless path.include?('nginx-dev')
        basename = File.basename(path)
        distro = File.basename(File.dirname(path))
        mkdir_p "/output/#{distro}"
        cp path, "/output/#{distro}/#{basename}"
      else
        puts "skipping #{path}"
      end
    end
  end

  files = Dir["/work/pkg/*/*.{deb,dsc,gz,xz}"]
  if files.any?
    puts "Placing #{files.size} files from /work/pkg into output directory"
    files.each do |path|
      unless path.include?('nginx-dev') || path.include?('/nginx_')
        basename = File.basename(path)
        distro = File.basename(File.dirname(path)).sub(/[-_].*/, '')
        mkdir_p "/output/#{distro}"
        cp path, "/output/#{distro}/#{basename}"
      else
        puts "skipping #{path}"
      end
    end
  end
end
