#!/bin/bash
set -e
if [ $# -ne 2 ]; then
	echo "Please specify 2 arguments: image:version subdir, for example:"
	echo "phusion/passenger_apt_automation_testbox_ubuntu_20_04:1.0.0 testbox-ubuntu-20.04"
	exit 1
fi
SELFDIR=`dirname "$0"`
SELFDIR=`cd "$SELFDIR" && pwd`
set -x
cd "$SELFDIR/$2"

docker buildx build --platform=linux/amd64,linux/arm64 --pull --no-cache --force-rm -t "$1" .
