#!/bin/bash
set -e
if [ $# -ne 2 ]; then
	echo "Please specify 2 arguments: image:version subdir, for example:"
	echo "phusion/passenger_apt_automation_testbox_ubuntu_16_04:1.0.0 testbox-ubuntu-16.04"
	exit 1
fi
SELFDIR=`dirname "$0"`
SELFDIR=`cd "$SELFDIR" && pwd`
set -x
cd "$SELFDIR/$2"

ARM_IMAGE="${1}-arm64"
AMD_IMAGE="${1}-amd64"

docker buildx build --platform linux/arm64 --pull --no-cache --force-rm -t $ARM_IMAGE .
docker buildx build --platform linux/amd64 --pull --no-cache --force-rm -t $AMD_IMAGE .
